### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by marcorossi5**
Updating docs

### CODE REVIEW

**Comment by marcorossi5** [comment]
Please, look if you are satisfied with the changings

**Comment by scarlehoff** [comment]
I added a few more points. Could you add also a explicit reference to the `alphas` (the python and the tensorflow) at the bottom?
I think with that this is complete enough for a release, @scarrazza  what do you think?

**Review by scarlehoff — APPROVED** [review]
This is ok by me.

**Comment by marcorossi5** [comment]
Great ! If @scarrazza agrees, we can merge

**Comment by scarlehoff** [comment]
Yes, I'll bump the version to 1.0 so that @scarrazza can merge this and then create the release for the paper.

**Review by scarrazza — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
